sudo: required
dist: trusty
language: node_js
node_js:
  - '10.0.0'

install:
  - npm install
  - npx ew-user-registry-lib-build
  - npx ew-utils-testbackend-build
  - npm run compile
  - npm run build

before_script:
  - npm run start-ganache > /dev/null &
  - npm run start-test-backend > /dev/null &
  - sleep 5
 
script:
  # - npm run lint
  - npm run test