version: '3'
services:
  origin_ui:
    image: "energyweb/origin-ui:${TAG}"
    ports:
      - "80:80"
    networks:
      - app-network
    env_file:
      - ./.env
    depends_on:
      - origin_backend

  market_matcher:
    image: "energyweb/market-matcher:${TAG}"
    env_file:
      - ./.env
    depends_on:
      - origin_backend

  event_listener:
    image: "energyweb/event-listener:${TAG}"
    env_file:
      - ./.env
    depends_on:
      - origin_backend

  solar_simulator:
    image: "energyweb/solar-simulator:${TAG}"
    ports:
      - "3032:3032"
    env_file:
      - ./.env
    depends_on:
      - origin_backend
    networks:
      - app-network

  origin_backend:
    image: "energyweb/origin-backend:${TAG}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network
    env_file:
      - ./.env
    volumes:
      - "./db:/var/db"

networks:
  app-network:
    driver: bridge