site_name: EW-Origin

nav:
  - Introduction: index.md
  - Getting started: getting-started.md
  - Architecture: architecture.md
  - User guides:
    - Onboarding: user-guide-onboarding.md
    - Device Management: user-guide-device-management.md 
  - SDK:
    - Traceability: traceability.md
    - Trade: trade.md
    - Device Registry: device-registry.md
    - Organizations: organizations.md
  - Cookbook:
    - How to deploy to Volta: volta-deployment.md

theme: readthedocs

plugins:
  - mermaid2
  - search
  - autolinks

extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js