image: docker.slock.it/build-images/node:10-alpine

stages:
  - build
  - deploy

build-pkg:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install 

push-to-registry:
  stage: deploy
  tags:
    - short-jobs
  only: # deploy only on  semantic versions tags
    - /^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/
  except:
    - branches
  dependencies:
    - build-pkg
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version -f version $CI_COMMIT_TAG
    - npm publish

push-to-github:
  stage: deploy
  variables:
    GITHUB_REPO_NAME: ew-utils-testbackend
    GIT_STRATEGY: clone
  only:
    - '/^v\d+\.\d+\.\d+\-release$/'
  tags:
    - short-jobs
  script:
    - echo -e "$CI_SSH_KEY" > /gitkey
    - chmod 0400 /gitkey
    - export GIT_SSH_COMMAND="/usr/bin/ssh -o StrictHostKeyChecking=no -i /gitkey"
    - git remote add external git@github.com:energywebfoundation/${GITHUB_REPO_NAME}.git
    - git push --force external HEAD:refs/heads/master
    - git tag | grep -v '\-release' | xargs git tag --delete 
    - git push --force external --tag $CI_COMMIT_TAG
    - rm /gitkey
